# Generated by Django 5.0.6 on 2024-07-04 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artobjects', '0003_alter_artobject_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moodboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('artobjects', models.ManyToManyField(related_name='moodboards', to='artobjects.artobject')),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moodboards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
