# Generated by Django 5.0.6 on 2024-07-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moodboards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moodboard',
            name='artobjects',
        ),
    ]
