# Generated by Django 5.0.6 on 2024-07-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artobjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artobject',
            name='api_object',
            field=models.CharField(max_length=300),
        ),
    ]
