# Generated by Django 5.0.6 on 2024-07-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artobjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artobject',
            name='img',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
