# Generated by Django 5.0.6 on 2024-07-09 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artobjects', '0003_artobject_moodboard'),
        ('moodboards', '0002_remove_moodboard_artobjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artobject',
            name='moodboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artobjects', to='moodboards.moodboard'),
        ),
    ]
